workflows:
  ios-squiz-onboarding:
    name: Squiz iOS Onboarding
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.squiz.messenger

      vars:
        XCODE_WORKSPACE: "Squiz.xcworkspace"
        XCODE_SCHEME: "Squiz"
        BUNDLE_ID: "com.squiz.messenger"

      xcode: 15.0
      cocoapods: default

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
        - pattern: 'feature/*'
          include: true
          source: true

    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "No Podfile found, skipping pod install"
          fi

      - name: Build iOS app
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Debug \
                     -destination 'generic/platform=iOS' \
                     clean build \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO

      - name: Run SwiftLint (if available)
        script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "SwiftLint not installed, skipping..."
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - dev@squiz.app
        notify:
          success: true
          failure: true
